apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: acore
  namespace: wow-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  name: acore
  mariaDbRef:
    name: wow-galera
  passwordSecretKeyRef:
    name: mariadb-acore
    key: password
  host: "%"
  maxUserConnections: 200
