apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wow-cluster-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
spec:
  project: default
  source:
    repoURL: https://github.com/Gravey158/athena-wow-cluster
    targetRevision: HEAD
    path: gitops/apps/wow-cluster
    directory:
      recurse: false
      include: '{namespace.yaml,my-cnf-configmap.yaml,mariadb-creds-sealed-secret.yaml,mariadb.yaml,databases.yaml,db-user.yaml,db-grants.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: wow-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
